manager: Carlos Witte
teamroom: Eng.DevSpacesImport.QE
units: 
    - unit: https://jira.devfactory.com/issues/?filter=94040
automation: 
    product agnostic: true
    product specific: 
        - product name: null
    description: Add QEPA (QE Process Automation tool) feature to automatically reject or approve tickets based on quality thresholds.
    effort: 42 # 42 days between investigation, validation and implementation - currently under test with real tickets
    impact: 20.00 # it should save 20% of the time from the QE Reviewer, because some reviews will be performed entirely by QEPA - QE Process Automation tool
