manager: Carlos Witte
teamroom: Eng.DevSpacesImport.QE
units: 
    - unit: https://jira.devfactory.com/issues/?filter=94040
automation: 
    product agnostic: true
    product specific: 
        - product name: null
    description: Add QEPA feature to automatically reject or approve some tickets based on quality thresholds.
    effort: 42
    impact: 0.20